name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy theme via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./wordpress-theme/

      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: ./wordpress-theme/
          retention-days: 1