name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Trigger WordPress theme update
        run: |
          curl -fsSL "https://aaronforum.com/wp-json/dfg/v1/package_update?secret=${{ secrets.WP_DEPLOY_SECRET }}&type=theme&package=aaron-forum-site"

      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: ./wordpress-theme/
          retention-days: 1